config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	
	# Users Admins

	get 'admins', to: 'admins#index'
	get 'admins/:id', to: 'admins#show', as: :admin


	# Photos
	#resources :photos
	
	get 'photos/new', as: :new_photos
	post 'photos', to: 'photos#create'
	get 'photos/:id', to:'photos#show'
	get 'photos/:id/edit', to: 'photos#edit'
	patch 'photos/:id', to: 'photos#update', as: :photo
	delete 'photos/:id', to: 'photos#destroy'
	get 'photos', to: 'photos#index'
	#Photos from user admin, relation between tables
	get 'photos/admin/:admin_id', to: 'photos#from_author'
	
	# Articles

	#Articulos de un usuario admin, relacion entre tablas
	get 'articles/admin/:admin_id', to: 'articles#from_author'

	get 'articles/new', to: 'articles#new', as: :new_articles
	get 'articles/:id', to: 'articles#show'
	get 'articles/:id/edit', to: 'articles#edit'
	post 'articles', to: 'articles#create'
	patch 'articles/:id', to: 'articles#update', as: :article
	delete 'articles/:id', to: 'articles#destroy'
	get 'articles', to: 'articles#index'
	

	# get "/bienvenida", to: "home#index"
	root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
  has_many :photos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	has_rich_text :content
	belongs_to :admin
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :admin
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @users_admins = Admin.all
  end
  def show
    @admin = Admin.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	#gem devise for authentica user admin is log in
	before_action :authenticate_admin!, only: [:new, :create, :edit, :destroy]	

	before_action :find_article, except: [:new, :create, :index, :from_author]
	def new
		@article = Article.new
	end
	def create
		@article = current_admin.articles.create(title: params[:article][:title],status: params[:article][:status],
		content: params[:article][:content])
		redirect_to @article
		#redirect_to articles_path
		#render json: @article
	end
	def show
	end
	def edit
	end
	def update
		@article.update(title: params[:article][:title],status: params[:article][:status],
		content: params[:article][:content])
		
		redirect_to @article
	end

	def destroy
		@article.destroy
		redirect_to root_path
	end
	
	def index
		@articles = Article.all		
	end

	def from_author
		@user_admin = Admin.find(params[:admin_id])	
	end

	def find_article
		@article = Article.find(params[:id])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: [:show,:edit,:update,:destroy]
  before_action :authenticate_admin!, except: [:show, :index]
  def new
    @photo = Photo.new
  end
  def create
    @photo = current_admin.photos.create(name: params[:photo][:name],code: params[:photo][:code])
    redirect_to @photo
  end
  def show
  end

  def edit
  end
  def update
    @photo = Photo.update(name: params[:photo][:name],code: params[:photo][:code])
    redirect_to @photo
  end
  def destroy
    @photo.destroy
    redirect_to root_path
  end
  def index
    @photos = Photo.all
  end

  def from_author
    @user_admin = Admin.find(params[:admin_id])
  end
  def find_photo
    @photo = Photo.find(params[:id])
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/admins/_admin.html.erb
<div class="card" style= "padding:15px;">
    <p class="text-uppercase">Usuario: <%=admin.name %> </p>
    <p>Status: <%=admin.email %> </p>
    <p><%= admin.created_at %></p>
    
    <%= link_to 'Ver mas', admin %>
</div>

app/views/admins/index.html.erb
<h1>Admins#index</h1>
<h4> Cantidad de Usuarios Administradores: <%= @users_admins.count %> </h4>

<%= render @users_admins %>

app/views/admins/show.html.erb
<div>
    <p class="text-uppercase">Usuario: <%=@admin.name %> </p>
    <p>Status: <%=@admin.email %> </p>
    <p><%= @admin.created_at %></p>

    <h2>Articulos publicados: </h2>
    <%= render @admin.articles %>

</div>

app/views/articles/_article.html.erb
<div class="card" style= "padding:15px;">
    <p class="text-uppercase">Titulo: <%=article.title %> </p>
    <p>Status: <%=article.status %> </p>
    <p><%= article.created_at %></p>
    <p >Publicado por: <%= article.admin.name %> </p>
    <%= link_to 'Ver mas', article %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form| %>
	<div id="form-style">
	<div>
		<%= form.label :title %>
		<%= form.text_field :title %> 
	</div>
	<div>
		<%= form.label :status %>
		<%= form.text_field :status %> 
	</div>

	<div>
		<%= form.label :content %>
		<%= form.rich_text_area :content %> 
	</div>
	
	<div>
		<%= form.submit %>
	</div>
	</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editar foto</h1>
<%= render 'articles/form' %>

app/views/articles/from_author.html.erb
<h1>Articulos que le pertenecientes a : <%=@user_admin.name %></h1>
<h3>Cantidad de Articulos: <%= @user_admin.articles.count %></h3>
<%= render @user_admin.articles %>

app/views/articles/index.html.erb
<h1>Mis Articulos</h1>

<%= render @articles %>

app/views/articles/new.html.erb
<%= render 'articles/form' %>

app/views/articles/show.html.erb
<h1> <%= @article.title %> </h1>

<p>Status: <%= @article.status %> </p>
<p>Articulo perteneciente al usuario: <%= @article.admin.name%></p> 
<div>
	<span>Contenido: <%= @article.content %></span> 
</div>

<div>
	<%= link_to 'Eliminar Articulo', @article, method: :delete %>
</div>

app/views/home/index.html.erb
<h1> Hello from the other side </h1>

<%= form_with url: "/", method: :get do |form| %>
  <%= form.label :query, "Search for:" %>
  <%= form.text_field :query %>
  <%= form.submit "Search" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogCodigof</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
        <p class="alert alert-primary"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= render 'partials/nav' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="nav bg-light">
    <li class="nav-item">
        <%= link_to 'Inicio', root_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Fotos', photos_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Articulos', articles_path, class:"nav-link" %>
    </li>
        <li class="nav-item">
        <%= link_to 'Usuarios', admins_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Nuevo Articulo', new_articles_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to 'Nueva Foto', new_photos_path, class:"nav-link" %>
    </li>

    <% if admin_signed_in? %>
        <li class="nav-item">
            <%= link_to 'Cerrar Sesion', destroy_admin_session_path, method: :delete, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to current_admin.name, root_path, class: "nav-link" %>       
        </li>    
    <% else %>
        <li class="nav-item">
            <%= link_to 'Iniciar Sesion', new_admin_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to 'Registrarse', new_admin_registration_path, class:"nav-link" %>
        </li>
    <% end %>


</nav>   

app/views/photos/_form.html.erb
<%=form_with(model: @photo, local: true ) do |f| %>

  <div>
    <%=  f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :code %>
    <%= f.text_field :code %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div class="card">
    <p>Nombre: <%= photo.name %></p>
    <p>Codigo: <%= photo.code %></p>
    <p>Creada: <%= photo.created_at %></p>
    <p>Publicada por: <%= photo.admin.name %></p>
    <%= link_to 'Ver foto', photo %>
</div>

app/views/photos/edit.html.erb
<%= render 'photos/form' %>

app/views/photos/from_author.html.erb
<h1>Fotos pertencientes al administrador: <%= @user_admin.name %> </h1>
<h3>Cantidad de fotos: <%= @user_admin.photos.count %> </h3>
<%= render @user_admin.photos %>

app/views/photos/index.html.erb
<h1>Mis photos </h1>

<%= render @photos%>

app/views/photos/new.html.erb
<h1>Photos#new</h1>

<%= render 'photos/form' %>

app/views/photos/show.html.erb
<h1>Nombre de la foto: <%= @photo.name %> </h1>

<h3>Codigo: <%= @photo.code %></h3>

<%= link_to 'Eliminar', @photo, method: :delete %>